# Require NPM_TOKEN in GitHub
# <REPO_URL>/settings/secrets/actions

name: Npm package

on:
  push:
    branches:
      - '*'
    tags:
      - v*

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Nodejs 10.16.3
        uses: actions/setup-node@master
        with:
          version: 10.16.3

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      # - name: Test
      #   run: npm test

  deploy:
    if: contains(github.ref, 'refs/tags/v')
    needs: build-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Nodejs 10.16.3
        uses: actions/setup-node@master
        with:
          version: 10.16.3

      - name: Publish to Npm
        run: |
          echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}' >> .npmrc
          npm publish
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
